run:
  timeout: 3m
  tests: true
  skip-dirs-use-default: true
  skip-dirs:
    - /usr/local/go
linters:
  enable:
    - errcheck
    - gosimple
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - errname
    - goconst
    - goimports
linters-settings:
  goimports:
    local-prefixes: "github.com/tccav/identity-service"